name: Automated Testing with .Net Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test_Chrome:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.json"]'
      env:
        browser: chromeheadless
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        path: |
              ./EverlightRadiology/Logs*
        if-no-files-found: warn

  Test_Edge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 18
    - name: Restore dependencies
      run: dotnet restore
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.json"]'
      env:
        browser: edgeheadless
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        path: |
          ./EverlightRadiology/Logs*
        if-no-files-found: warn